spring:
  datasource:
    url: jdbc:mysql:replication://10.9.2.22:3306,10.9.2.42:3306/baymax?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: baymax-dev
    password: baymax_bjdev
  redis:
    sentinel:
      nodes: 10.9.2.13:26379,10.9.2.23:26379,10.9.2.33:26379
      master: mymaster
    password: 7lkddfdfdff223D
baymax:
  mongo:
    - bean-name: messageMongoTemplate
      uri: mongodb://baymaxms:baymax_message@10.9.2.11:27017,10.9.2.21:27017,10.9.2.31:27017/baymaxMessage